### ISSUE TITLE
Can i upload srt file downloaded from online

### ISSUE THREAD

**Issue by balayokesh** [nhcarrigan/subtitle-translations#4]
I have the `srt` file for Titanic movie.  I downloaded it from [moviessubtitlesrt.com](https://moviesubtitlesrt.com/hollywood/titanic-1997-english-subtitles-download/).  Can I make a pull request by adding that file to `subtitles/english`

**Comment by nhcarrigan** [comment]
Hi there,

This is actually a prototype for freeCodeCamp, so at the moment is not accepting outside files.

**Comment by balayokesh** [comment]
oh ok
